version: '3.8'

services:
  login-exam:
    container_name: login-exam
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: npm start