version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: npm start
  
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080/api