version: '3.8'

services:
  nextjs-app:
    container_name: login-exam
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # command: npm run build && npm run start
    command: npm run dev